apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluent
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 10
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Tag kube.*
        Path /var/log/containers/*.log
        Parser docker
        Mem_Buf_Limit 5MB
        Skip_Long_Lines Off
        Refresh_Interval 10
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
        Strip_Underscores On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           Off
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes
        Add_prefix kubernetes.
    [FILTER]
        Name modify
        Match kube.*
        Copy kubernetes.container_name tags.container
        Copy log message
        Copy kubernetes.container_image tags.image
        Copy kubernetes.namespace_name tags.namespace
    [FILTER]
        Name nest
        Match kube.*
        Operation nest
        Wildcard tags.*
        Nested_under tags
        Remove_prefix tags.

    [OUTPUT]
        Name            es
        Match           kube.*
        Index           fluent-bit-kube
        Host            elasticsearch-master.monitoring.svc.cluster.local
        Port            9200 
        Logstash_Format Off
        Time_Key       @timestamp
        Type            flb_type
        Replace_Dots    On
        Retry_Limit     False
        Trace_Error     Off
