apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
  - name: stress-container
    image: progrium/stress
    resources:
      limits:
        cpu: "2"
        memory: "512Mi"
      requests:
        cpu: "1"
        memory: "256Mi"
    command:
      - "stress"
      - "--cpu"
      - "2" 
      - "--io"
      - "4"
