apiVersion: v1
data:
  04-prometheus-additional.yaml: LSBqb2JfbmFtZTogInByb21ldGhldXMiCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSB0YXJnZXRzOiBbInByb21ldGhldXMtc2VydmljZS5tb25pdG9yaW5nLnN2Yy5jbHVzdGVyLmxvY2FsOjgwIl0K
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
