apiVersion: v1
kind: Service
metadata:
  name: flask-alertmanager
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: alertmanager
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: flask-alertmanager
